### ISSUE TITLE
Problem with working

### ISSUE THREAD

**Issue by Xartek-art** [EvotecIT/O365Synchronizer#11]
Some time ago I came across your script, the so-called O365Synchronizer. Unfortunately, my problem is that when executing the script I get a "no permissions" message (as I understand it, the application itself).

Application added to the tenant, permissions according to your entry as below:
User.Read.All - to read users
OrgContact.Read.All - to read contacts
Contacts.ReadWrite - to write contacts

I have problem with permission. I paste error below:
0365Synchronizer.psm1* X

```
Import-Module 0365 Synchronizer
2
3 $ClientID = 'e4540c94
*Rez4C8E1
5
6
7
8
4 $TenantID = 'b98a5480
$ClientSecret = 'aHD8Q
$Credentials = [pscredential]::new($ClientID, (ConvertTo-SecureString SClientSecret -AsPlainText -Force))
Connect-MgGraph -ClientSecretCredential $Credentials -TenantId $TenantID -Nowelcome
9
10
11
# Synchronization per user or multiple users in one
Sync-0365 Personal Contact -UserId 'b
-Verbose -Member Types 'Contact', 'Member' -GuidPrefix '0365 Synchronizer
Format-Table*
VERBOSE: Filtering out user Warranty
VERBOSE: Filtering out user y.
VERBOSE: Filtering out user z.
VERBOSE: Filtering out user zakupy.
VERBOSE: Filtering out user zgloszenia
[!] Getting user contacts for b
by no assigned licenses
by no assigned licenses
by account is disabled
-propo
[i] Processing
Cannot index into a null array.
va
m by no assigned licenses
by no assigned licenses
failed. Error: [ErrorAccessDenied] : Access is denied. Check credentials and try again.
n
At C:\Program Files\WindowsPowerShell\Modules\0365 Synchronizer\1.0.2\0365Synchronizer.psm1:1821 char:9
$Contact = $Existing Contacts [$Entry]
: InvalidOperation: (:) [], RuntimeException
+ CategoryInfo
+ FullyQualifiedErrorId : NullArray
[+] Creating
[!] Failed to create
or
[i] Processing
Cannot index into a null array.
va because: [Error AccessDenied] : Access is denied. Check credentials and try again.
At C:\Program Files\Windows PowerShell\Modules\0365 Synchronizer\1.0.2\0365 Synchronizer.psm1:1821 char:9
$Contact = $Existing Contacts [$Entry]
+
+ CategoryInfo
: InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray
```

What type of permission I miss ?

**Comment by PrzemyslawKlys** [comment]
Hey,

Please provide cleaned up log without those broken lines, and some weird formatting. 
Did you "admin" accepted those permissions in Graph? Maybe a screenshot would be worth it?

**Comment by Xartek-art** [comment]
> Hey,
> 
> Please provide cleaned up log without those broken lines, and some weird formatting. Did you "admin" accepted those permissions in Graph? Maybe a screenshot would be worth it?

![image](https://github.com/user-attachments/assets/ac4a26a6-d880-4b9a-9408-f23bbc5f8c57)

**Comment by Xartek-art** [comment]
That's true. This solution solve my problem !
Another way, perfect solution for tenants where admins don't have enrolled intune or doesn't have too much skills. Biggest congratulations for you.
Thanks for fast response and recognize problem.
