### ISSUE TITLE
Problem with some / random accounts

### ISSUE THREAD

**Issue by szkwarekb** [EvotecIT/O365Synchronizer#19]
With some accounts I have a message: 

[!] Getting user contacts for xxxxxx@xxx.com  failed. Error: Expected literal (number, boolean, or null). Was '<'.

**Comment by PrzemyslawKlys** [comment]
Not really helpful and not much to go on...

**Comment by szkwarekb** [comment]
OK, OK, maybe I'll explain, I sync accounts and in a large amount of accounts there is no problem at all 
But today started problems with accounts - which are no different from the rest, I updated the modulus, ran it on another hardware - but the problem persists. 
If you think this is too little data for you - please point me to the places I should check. 
Error that occurs: 

VERBOSE: Filtering out user xxxxxxxx by account is disabled
[!] Getting user contacts for xxxxxxx failed. Error: Expected literal (number, boolean, or null). Was '<'.
PS C:\Users\xxxxx>

**Comment by szkwarekb** [comment]
and as I said, with other accounts - I don't have any problem :)


Synchronizacja kontaktów dla użytkownika: xxxxxx@xxxxx
[i] xxxxxx has x contacts, out of which x synchronized.
[i] Users to process: xxxx Contacts to process: xxx
[i] Processing xxxxxx
[i] Processing xxxxxx
[i] Processing xxxxx
[i] Processing xxxxx

**Comment by szkwarekb** [comment]
OK - I will check - Thanks
