### ISSUE TITLE
Contacts that have WorkPhone or MobilePhone in Exchange don't transfer phone through to personal contacts.

### ISSUE THREAD

**Issue by coolgooseman** [EvotecIT/O365Synchronizer#2]
All the contacts that are local users sync with mobile and or business numbers to my phone, but once i start syncing mail contacts they don't do the same.
In Exchange the contacts have a phone number, but once theyre synced to my phone they don't show it, the name, function title etc and all sync properly. Just the phone number doesnt.

Is this intended or something that can be fixed?
I can't figure out how to get it to sync when looking at the source code.
The mail contacts were created with the tenant sync from this module aswell.

**Comment by PrzemyslawKlys** [comment]
It can be fixed/improved, or maybe just missing configuration? 

- I guess you are using `Sync-O365Contact`

This code uses Get-MgUser to get properties. If you check those $UsersToSync do you see MobilePhonee/Phone/HomePhone? 

```powershell
# Source tenant
$ClientID = '9e1b3c36'
$TenantID = 'ceb371f6'
$ClientSecret = 'NDE8Q'

$Credentials = [pscredential]::new($ClientID, (ConvertTo-SecureString $ClientSecret -AsPlainText -Force))
Connect-MgGraph -ClientSecretCredential $Credentials -TenantId $TenantID -NoWelcome

$UsersToSync = Get-MgUser | Select-Object -First 5

# Destination tenant
$ClientID = 'edc4302e'
Connect-ExchangeOnline -AppId $ClientID -CertificateThumbprint '2EC710' -Organization 'xxxxx.onmicrosoft.com'
Sync-O365Contact -SourceObjects $UsersToSync -Domains 'evotec.pl', 'gmail.com' -Verbose -WhatIf -LogPath 'C:\Temp\Logs\O365Synchronizer.log' -LogMaximum 5
```

In the code there is a command Convert-GraphObjectToContact that translates this to contact so it should work, but maybe something is wrong.

**Comment by coolgooseman** [comment]
Hey,
I'm sorry but i meant syncing contacts from the GAL, to your local address book. Not from 1 tenant to the other. My bad for not clarifying.
The contacts that i'm syncing are transferred from another tenant.

So i sync a mailcontact to my own address list from the GAL with this command:

Sync-O365PersonalContact -UserId 'myuser@test.nl' -Verbose -MemberTypes 'Contact', 'Member' -GuidPrefix 'O365Synchronizer' | Format-Table *

But then the number which does show up in the GAL, doesn't show up in my local address book.

As far as i understand the script the issue could be located in Set-O365WrapperPersonalContact.ps1
I think the mobilephone/workphone value gets lost somewhere in here.
But i do not know how to troubleshoot this.

Thanks for responding.

**Comment by GrubiHD** [comment]
@coolgooseman 
were you able to fix/troubleshoot this problem. I am facing the same problem right now and it would help having a solution and not having to go through the entire code.

**Comment by coolgooseman** [comment]
@GrubiHD Never got around to it. Don't think i'll do anytime soon.

**Comment by PrzemyslawKlys** [comment]
This should be fixed in new version
