### ISSUE TITLE
Beginner's Implementation Guide?

### ISSUE THREAD

**Issue by ccatlett1984** [EvotecIT/O365Synchronizer#4]
It seems this project assumes a base-level of knowledge for implementation, and is missing important details.
Would be nice to have a guide to refer folks to, so they can implement this project in their environments.

**Comment by PrzemyslawKlys** [comment]
I am not sure how to help you. I've blogged about this module:
- https://evotec.xyz/syncing-global-address-list-gal-to-personal-contacts-and-between-office-365-tenants-with-powershell/

It tries to help and show the functionality. Does that help?
