### ISSUE TITLE
MemberTypes

### ISSUE THREAD

**Issue by PiotrKaniaspravia** [EvotecIT/O365Synchronizer#5]
Hello
Your solution works great.
But I'd like to ask how we can filter address book or membertypes option. We'd like to filter users based on company attribute. 
Thanks !

**Comment by PrzemyslawKlys** [comment]
If you mean `Sync-O365PersonalContact` then this is not something I've added. This would need to be added, along with any other filtering.

**Comment by PiotrKaniaspravia** [comment]
Yes, I'm using Sync-O365PersonalContact. It was really easy to modify O365Synchronizer.psm1 in folder  **C:\Program Files\WindowsPowerShell\Modules\O365Synchronizer\0.0.4**
Company attribute is not imported from msgraph, but I've created a filter based on email address string. 
Thanks a lot !

**Comment by PiotrKaniaspravia** [comment]
It would be nice to add. But in my environment it works like a charm (modified filter in psm1 module file).
Once again - it is really great tool - it should be added on exchange default feature :-)

**Comment by PrzemyslawKlys** [comment]
Ye i have some ideas on how to allow for filtering in more dynamic way than hardcoding like this, just busy with other stuff. But I will sit down to it sooner or later

**Comment by PrzemyslawKlys** [comment]
With new version:

```powershell
    Sync-O365PersonalContact -UserId 'przemyslaw.klys@test.pl' -Verbose -MemberTypes 'Contact', 'Member' -GuidPrefix 'O365Synchronizer' -WhatIf -PassThru {
        Sync-O365PersonalContactFilter -Type Include -Property 'CompanyName' -Value 'OtherCompany*','Evotec*' -Operator 'like' # filter out on CompanyName
        Sync-O365PersonalContactFilterGroup -Type Include -GroupID 'e7772951-4b0e-4f10-8f38-eae9b8f55962' # filter out on GroupID
    } | Format-Table
``` 

Should be released this week.
