### ISSUE TITLE
suggestion: Import specific groups instead of whole GAL

### ISSUE THREAD

**Issue by Soulfulsysadmin** [EvotecIT/O365Synchronizer#6]
Hi there, I'm watching your project here for updates because it is exactly what I need for my tenant and has worked pretty well in testing aside from a few things, one being to put the contacts into another folder to not flood the user's existing contacts, but you already mentioned working on that.

Would it be possible to import (synchronize) a specific group of people into the user's mailbox contacts instead of the whole GAL, because our GAL contains a lot of accounts that the regular user does not need to know about. (test accounts, printers etc.). or perhaps specify which contacts not to import.

Otherwise, great work. I was getting desperate for a solution to Microsoft's undercooked contact system before someone on reddit linked your module. 👍

**Comment by PrzemyslawKlys** [comment]
it all makes sense to have additional filtering

**Comment by PrzemyslawKlys** [comment]
With new version:

```powershell
    Sync-O365PersonalContact -UserId 'przemyslaw.klys@test.pl' -Verbose -MemberTypes 'Contact', 'Member' -GuidPrefix 'O365Synchronizer' -WhatIf -PassThru {
        Sync-O365PersonalContactFilter -Type Include -Property 'CompanyName' -Value 'OtherCompany*','Evotec*' -Operator 'like' # filter out on CompanyName
        Sync-O365PersonalContactFilterGroup -Type Include -GroupID 'e7772951-4b0e-4f10-8f38-eae9b8f55962' # filter out on GroupID
    } | Format-Table
``` 

Should be released this week.
