### ISSUE TITLE
ContactFolderID

### ISSUE THREAD

**Issue by ChimeraArmadillo** [EvotecIT/O365Synchronizer#9]
I have been battling this error all night...

cmdlet New-MgUserContactFolderContact at command pipeline position 1
Supply values for the following parameters:
ContactFolderId:

When any existing contact synchronizes and gets to the new contact I get the above message.

When synchronizing the above user individually (Users to process: 310 Contacts to process: 0) to get all new contacts I get the above message at the first contact.

Is this a bug in graph or am I way off?

**Comment by PrzemyslawKlys** [comment]
Unfortunetly it's my doing, fixed in 1.0.2. I've made mistake in assuming something is null when it was empty string
